compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  greenfinity:
    # npmPublishRegistry: "https://registry.npmjs.org/"
    npmPublishRegistry: "https://npm.greenfinity.hu"
    npmRegistryServer: "https://npm.greenfinity.hu"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
